import sharp from 'sharp';
const f = process.argv[2];
const { data, info } = await sharp(f).raw().toBuffer({ resolveWithObject: true });
const W = info.width, C = info.channels;
const L = (x, y) => { const i = (y * W + x) * C; return 0.2126 * data[i] + 0.7152 * data[i + 1] + 0.0722 * data[i + 2]; };
const rowMean = y => { let s = 0, n = 0; for (let x = 0; x < W; x += 4) { s += L(x, y); n++; } return s / n; };
const colMean = x => { let s = 0, n = 0; for (let y = 0; y < 180; y += 2) { s += L(x, y); n++; } return s / n; };
console.log('ROW MEAN, top 60 rows:');
let o = []; for (let y = 0; y < 60; y++) o.push('y' + String(y).padStart(2) + ':' + rowMean(y).toFixed(1));
console.log(o.join(' '));
console.log('\nROW MEAN y150-260 (room line + horizon):');
o = []; for (let y = 150; y < 262; y += 2) o.push('y' + y + ':' + rowMean(y).toFixed(1));
console.log(o.join(' '));
console.log('\nCOL MEAN (y0-180), left 40 cols:');
o = []; for (let x = 0; x < 40; x++) o.push('x' + x + ':' + colMean(x).toFixed(1));
console.log(o.join(' '));
console.log('\nCOL MEAN (y0-180), right 40 cols:');
o = []; for (let x = W - 40; x < W; x++) o.push('x' + x + ':' + colMean(x).toFixed(1));
console.log(o.join(' '));
