-- ===============================================================
-- Warehouse access roles — who may touch someone else's yard.
--
-- Before this, the warehouse recognised two kinds of person: the owner, and
-- the renter of a given bay. A visitor was kept out of most things only by the
-- client hiding buttons, which is not a control — the RPCs are callable from a
-- console.
--
-- The model now:
--   owner    — everything.
--   staff    — a player hired into the OWNER'S corporation (corp_members).
--              May work the floor: use the workstation, and carry crates INTO
--              any bay. May NOT withdraw from a bay, may NOT spend the owner's
--              money, may NOT see what is stored in a bay.
--   renter   — their own bay, and nothing else.
--   visitor  — may look. Nothing else.
--
-- Spending was already safe and is untouched: wh_buy_unit / wh_upgrade_tier
-- resolve the warehouse with "where owner_id = auth.uid()", so no one but the
-- owner can ever charge the owner. wh_withdraw was already renter-only.
--
-- Idempotent. Generated by tools/make-access-migration.mjs from the original
-- warehouse migration, so the untouched parts of these functions are
-- byte-identical to what is live.
-- ===============================================================

-- ─── 👷 wh_is_staff — is p_uid hired into the warehouse owner's corp? ────────
-- Wrapped in an exception handler on purpose: a deployment without the
-- corporations tables simply has no staff, rather than breaking every crate
-- that anyone tries to store.
create or replace function public.wh_is_staff(p_warehouse_id uuid, p_uid uuid default auth.uid())
returns boolean language plpgsql stable security definer set search_path = public as $$
declare v_owner uuid; v_corp uuid; v_ok boolean := false;
begin
  if p_uid is null or p_warehouse_id is null then return false; end if;
  select owner_id into v_owner from public.wh_warehouses where id = p_warehouse_id;
  if v_owner is null then return false; end if;
  if v_owner = p_uid then return true; end if;          -- the owner is trivially staff
  begin
    -- The owner's corporation: the one they were hired into, else one they founded.
    select corp_id into v_corp from public.corp_members where user_id = v_owner limit 1;
    if v_corp is null then
      select id into v_corp from public.corporations where founder_id = v_owner limit 1;
    end if;
    if v_corp is null then return false; end if;        -- an owner with no corp has no staff
    select exists (
      select 1 from public.corp_members m where m.corp_id = v_corp and m.user_id = p_uid
      union all
      select 1 from public.corporations c where c.id = v_corp and c.founder_id = p_uid
    ) into v_ok;
  exception when others then
    return false;                                        -- no corp tables in this deployment
  end;
  return coalesce(v_ok, false);
end; $$;
grant execute on function public.wh_is_staff(uuid, uuid) to authenticated;

-- ─── 📦 wh_store_crate — owner, hired staff, or the bay's own renter ─────────
create or replace function public.wh_store_crate(p_crate_id uuid, p_unit_id uuid default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid(); v_c public.wh_crates; v_s public.wh_shipments;
  v_u public.wh_units; v_w public.wh_warehouses; v_cfg jsonb := public.wh_config();
  v_carry numeric; v_tier integer; v_new jsonb; k text; v_qty numeric; v_done integer;
begin
  if v_uid is null then return jsonb_build_object('ok', false, 'reason', 'not_signed_in'); end if;
  select * into v_c from public.wh_crates where id = p_crate_id for update;
  if not found then return jsonb_build_object('ok', false, 'reason', 'no_crate'); end if;
  if v_c.stored then return jsonb_build_object('ok', false, 'reason', 'already_stored'); end if;
  select * into v_s from public.wh_shipments where id = v_c.shipment_id for update;
  if not found or v_s.status = 'cancelled' then return jsonb_build_object('ok', false, 'reason', 'no_shipment'); end if;
  if v_s.eta_at > now() then
    return jsonb_build_object('ok', false, 'reason', 'in_transit', 'eta_at', v_s.eta_at);
  end if;
  select * into v_u from public.wh_units where id = coalesce(p_unit_id, v_s.unit_id) for update;
  if not found then return jsonb_build_object('ok', false, 'reason', 'no_unit'); end if;
  select * into v_w from public.wh_warehouses where id = v_u.warehouse_id;
  -- ⚠ THE BAY MUST BELONG TO THE SHIPMENT. p_unit_id is client-supplied and only
  -- DEFAULTS to the shipment's bay, so this check is the whole ballgame. An
  -- earlier build only asked "is the caller the owner or the renter OF THE
  -- TARGET BAY" — which a warehouse owner satisfies trivially by renting one
  -- cheap bay in some THIRD player's warehouse. Executed attack: Bob owns the
  -- warehouse, so he legitimately receives Alice's crate ids in order to unload
  -- her truck; he rents a bay in Carol's warehouse for 1,200 Cinder and stores
  -- Alice's crates into it. Alice's bay stays empty, her shipment reports
  -- "stored 10/10", and Bob withdraws her goods as his own.
  -- The bay must be in the SAME warehouse the load was sent to, and rented by
  -- the SAME player who sent it. (Same-warehouse overflow into another of the
  -- sender's own bays stays legal; anything else does not.)
  if v_u.warehouse_id is distinct from v_s.warehouse_id
     or v_u.renter_id is distinct from v_s.sender_id then
    return jsonb_build_object('ok', false, 'reason', 'wrong_unit');
  end if;
  -- The rental has to be current, exactly as wh_send_shipment already demands.
  -- Allowing a lapsed bay to keep accepting deposits contradicted that gate.
  if v_u.rent_until is not null and v_u.rent_until < now() then
    return jsonb_build_object('ok', false, 'reason', 'rental_expired', 'rent_until', v_u.rent_until);
  end if;
  -- …and the caller still has to be someone entitled to touch this warehouse:
  -- the owner (who does the hauling), a worker hired into the owner's corp, or
  -- the renter themselves. Staff may only ever put crates IN — wh_withdraw
  -- stays renter-only, so a hired hand can never empty a customer's bay.
  if v_w.owner_id is distinct from v_uid
     and v_u.renter_id is distinct from v_uid
     and not public.wh_is_staff(v_w.id, v_uid) then
    return jsonb_build_object('ok', false, 'reason', 'not_allowed');
  end if;
  -- 🏋 Can this player physically lift it? Client-side HUD is UX; this is the rule.
  v_tier  := coalesce((select tier from public.wh_lifters where user_id = v_uid), 0);
  v_carry := ((v_cfg -> 'lifters') -> v_tier ->> 'carry_kg')::numeric;
  if v_c.weight_kg > v_carry then
    return jsonb_build_object('ok', false, 'reason', 'too_heavy',
      'weight_kg', v_c.weight_kg, 'carry_kg', v_carry, 'lifter_tier', v_tier);
  end if;
  -- 📦 Room in the bay? This is the "You need to open storage unit space" gate.
  if v_u.used_kg + v_c.weight_kg > v_u.capacity_kg then
    return jsonb_build_object('ok', false, 'reason', 'no_room',
      'used_kg', v_u.used_kg, 'capacity_kg', v_u.capacity_kg, 'weight_kg', v_c.weight_kg);
  end if;
  v_new := v_u.contents;
  for k, v_qty in select key, (value)::numeric from jsonb_each_text(v_c.payload) loop
    v_new := v_new || jsonb_build_object(k, coalesce((v_new ->> k)::numeric, 0) + v_qty);
  end loop;
  update public.wh_units set contents = v_new, used_kg = used_kg + v_c.weight_kg, updated_at = now()
    where id = v_u.id;
  update public.wh_crates set stored = true, stored_at = now() where id = v_c.id;
  select count(*) into v_done from public.wh_crates where shipment_id = v_s.id and stored = true;
  update public.wh_shipments set crates_stored = v_done,
    status = case when v_done >= crates_total then 'stored' else 'arrived' end
    where id = v_s.id;
  return jsonb_build_object('ok', true, 'crate_id', v_c.id, 'unit_id', v_u.id,
    'bay_no', v_u.bay_no, 'weight_kg', v_c.weight_kg,
    'used_kg', v_u.used_kg + v_c.weight_kg, 'capacity_kg', v_u.capacity_kg,
    'crates_stored', v_done, 'crates_total', v_s.crates_total,
    'shipment_done', (v_done >= v_s.crates_total));
end; $$;
grant execute on function public.wh_store_crate(uuid, uuid) to authenticated;

-- ─── 🏬 wh_warehouse_json — now reports viewer_role ─────────────────────────
create or replace function public.wh_warehouse_json(p_warehouse_id uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_uid uuid := auth.uid(); v_w public.wh_warehouses; v_is_owner boolean;
        v_is_staff boolean; v_role text;
begin
  if v_uid is null then return jsonb_build_object('ok', false, 'reason', 'not_signed_in'); end if;
  select * into v_w from public.wh_warehouses where id = p_warehouse_id;
  if not found then return jsonb_build_object('ok', false, 'reason', 'no_warehouse'); end if;
  v_is_owner := (v_w.owner_id = v_uid);
  -- Hired = a member of the same corporation as the owner. Never true for the
  -- owner themselves, so the two roles stay disjoint in the payload.
  v_is_staff := (not v_is_owner) and public.wh_is_staff(v_w.id, v_uid);
  v_role := case
              when v_is_owner then 'owner'
              when v_is_staff then 'staff'
              when exists (select 1 from public.wh_units u
                            where u.warehouse_id = v_w.id and u.renter_id = v_uid) then 'renter'
              else 'visitor'
            end;
  return jsonb_build_object(
    'ok', true,
    'is_owner', v_is_owner,
    -- The client gates every control off these two. They are advisory for the
    -- UI only: each RPC re-checks for itself, because a hidden button is not a
    -- permission.
    'is_staff', v_is_staff,
    'viewer_role', v_role,
    'config', public.wh_config(),
    'warehouse', jsonb_build_object(
      -- The owner's raw auth.users id is the same class of identifier we mask
      -- for renters; `is_owner` already tells the caller what they need.
      'id', v_w.id, 'owner_id', case when v_is_owner then v_w.owner_id else null end,
      'owner_name', v_w.owner_name,
      'node_id', v_w.node_id, 'tier', v_w.tier, 'units_total', v_w.units_total,
      'max_units', ((public.wh_config() -> 'tiers') -> (v_w.tier - 1) ->> 'max_units')::integer,
      'open_to_all', v_w.open_to_all),
    'units', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', u.id, 'bay_no', u.bay_no,
        -- ⚠ MASKED. Tightening the table RLS moved this leak into the rpc and
        -- made it worse: any authenticated player could read a warehouse id out
        -- of wh_directory() and pull back, per bay, the renter's RAW auth.users
        -- id, their name, how full their bay was and when their rent expired.
        -- Exporting another player's auth uid is worse than the contents leak
        -- it replaced, and used_kg + identity IS the "which bays are worth
        -- diverting" list this module claims not to publish. You see a bay's
        -- occupant only if you own the building or rent that bay.
        'renter_id',   case when v_is_owner or u.renter_id = v_uid then u.renter_id   else null end,
        'renter_name', case when v_is_owner or v_is_staff or u.renter_id = v_uid then u.renter_name else null end,
        'used_kg',     case when v_is_owner or v_is_staff or u.renter_id = v_uid then u.used_kg else null end,
        'rent_until',  case when v_is_owner or u.renter_id = v_uid then u.rent_until  else null end,
        'occupied',    (u.renter_id is not null),
        -- Masked too: capacity ranks the bays by who has paid to expand.
        'capacity_kg', case when v_is_owner or v_is_staff or u.renter_id = v_uid then u.capacity_kg else null end,
        'contents', case when v_is_owner or u.renter_id = v_uid then u.contents else '{}'::jsonb end,
        -- `= v_uid` on a NULL renter_id yields NULL, not false. An unrented bay
        -- is not 'maybe mine'.
        'mine', coalesce(u.renter_id = v_uid, false)
      ) order by u.bay_no) from public.wh_units u where u.warehouse_id = v_w.id), '[]'::jsonb),
    'shipments', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id, 'sender_name', s.sender_name, 'unit_id', s.unit_id,
        'origin_kind', s.origin_kind, 'origin_label', s.origin_label,
        'node_level', s.node_level, 'free_city', s.free_city,
        'eta_hours', s.eta_hours, 'eta_at', s.eta_at, 'sent_at', s.sent_at,
        'weight_kg', s.weight_kg, 'status', case when s.status = 'transit' and s.eta_at <= now() then 'arrived' else s.status end,
        'crates_total', s.crates_total, 'crates_stored', s.crates_stored,
        'crates', coalesce((select jsonb_agg(jsonb_build_object(
            'id', c.id, 'crate_no', c.crate_no, 'payload', c.payload, 'weight_kg', c.weight_kg)
            order by c.crate_no)
          from public.wh_crates c where c.shipment_id = s.id and c.stored = false), '[]'::jsonb)
      ) order by s.eta_at)
      from public.wh_shipments s
      where s.warehouse_id = v_w.id and s.status in ('transit', 'arrived')
        and (v_is_owner or s.sender_id = v_uid)), '[]'::jsonb),
    'lifter_tier', coalesce((select tier from public.wh_lifters where user_id = v_uid), 0),
    'wallet', (select jsonb_build_object('cinder', cinder, 'aza', sovereigns)
               from public.user_progress where user_id = v_uid)
  );
end; $$;
grant execute on function public.wh_warehouse_json(uuid) to authenticated;
